// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {template} from '../models';
import {models} from '../models';

export function DeleteTemplate(arg1:number):Promise<void>;

export function ExportFile(arg1:string,arg2:template.FromConfig,arg3:Array<template.MappingInput>):Promise<void>;

export function GetFileHeaders(arg1:string,arg2:number,arg3:string,arg4:string):Promise<any>;

export function GetTemplateByID(arg1:number):Promise<models.Template>;

export function GetTemplates():Promise<Array<models.Template>>;

export function GetVersion():Promise<string>;

export function SaveTemplate(arg1:string,arg2:template.FromConfig,arg3:Array<template.MappingInput>):Promise<void>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function UpdateTemplate(arg1:number,arg2:string,arg3:template.FromConfig,arg4:Array<template.MappingInput>):Promise<void>;
