// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function ExportFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportFile'](arg1, arg2, arg3);
}

export function GetFileHeaders(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFileHeaders'](arg1, arg2, arg3, arg4);
}

export function GetTemplateByID(arg1) {
  return window['go']['main']['App']['GetTemplateByID'](arg1);
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function SaveTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTemplate'](arg1, arg2, arg3);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function UpdateTemplate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTemplate'](arg1, arg2, arg3, arg4);
}
